---
on:
  push:
    branches:
      - main
    paths:
      - "apps/cms/**"
  pull_request:
    paths:
      - "apps/cms/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Resolve Dependencies
        run: pnpm --filter cms install --frozen-lockfile

      - name: Check code
        run: pnpm --filter cms run lint

  # migration:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [18]

  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   needs:
  #     - lint

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "pnpm"

  #     - name: Run migration
  #       run: pnpm --filter cms run migrate
