---
on:
  push:
    branches:
      - main
    paths:
      - "apps/cms/**"
  pull_request:
    paths:
      - "apps/cms/**"
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile

      - name: Check code
        run: bun --cwd=apps/cms run lint

  migration:
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile

      - name: Run migration
        run: bun --cwd=apps/cms run migrate
        env:
          DEV: true
          CONTENTFUL_ENV: ${{ github.ref == 'refs/heads/main' && 'master' || 'develop' }}
          CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
