---
on:
 workflow_run:
    workflows:
      - cms
    types:
      - completed

jobs:
  checkTypegen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    env:
      DEV: true
      CONTENTFUL_ENV: ${{ vars.CONTENTFUL_ENV }}
      CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}

    needs:
      - migration

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Resolve Dependencies
        run: pnpm --filter=web install --frozen-lockfile

      - name: Check type of content model is generated
        run: |
          pnpm --filter=web run typegen && git diff --exit-code apps/web/src/types
        env:
          CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
