---
on:
 workflow_run:
    workflows:
      - cms
    types:
      - completed

jobs:
  checkTypegen:
    runs-on: ubuntu-latest
    env:
      DEV: true
      CONTENTFUL_ENV: ${{ vars.CONTENTFUL_ENV }}
      CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}

    needs:
      - migration

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile

      - name: Check type of content model is generated
        run: |
          bun --cwd=apps/web run typegen && git diff --exit-code apps/web/src/types
        env:
          CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
