---
on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
  pull_request:
    paths:
      - "apps/web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Resolve Dependencies
        run: pnpm install
      - name: Check code
        run: pnpm run lint --filter web

      - name: Build
        run: pnpm run build --filter web
