---
on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
  pull_request:
    paths:
      - "apps/web/**"
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile
      - name: Check code
        run: bun --cwd=apps/web run lint

      - name: Build
        run: bun --cwd=apps/web run build
        env:
          DEV: true
          CONTENTFUL_ENV: ${{ github.ref == 'refs/heads/main' && 'master' || 'develop' }}
          CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
